services:
  backend:
    build: ./Application-Code/backend
    # image: rakshithrpoojary/backend:9
    ports:
      - "4000:4000"
    networks:
      - mern_network
    environment:
      MONGO_CONN_STR: mongodb://admin:admin123@mongodb:27017/mydatabase?authSource=admin
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin123
      PORT: 4000
    depends_on:
      - mongodb

  frontend:
    build: ./Application-Code/frontend
    # image: rakshithrpoojary/frontend:9
    ports:
      - "3001:3000"
    networks:
      - mern_network
    environment:
      REACT_APP_BACKEND_URL: http://13.201.96.51:4000/api/tasks

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local # Persist MongoDB data locally
